# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 08:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название стиля')),
                ('style', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Описание стиля')),
            ],
            options={
                'verbose_name': 'Стили отображения слоёв',
                'managed': True,
                'ordering': ['title'],
            },
        ),
    ]
