# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0004_tilelayer_tms'),
        ('vector_style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatalayerStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.CharField(blank=True, max_length=254, null=True)),
                ('datalayer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='leaflet_storage.DataLayer', verbose_name='Слой')),
            ],
            options={
                'ordering': ['datalayer__description'],
                'managed': True,
                'verbose_name': 'Настройка стилей слоёв',
            },
        ),
    ]
